services:
  cli-proxy-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        COMMIT: ${COMMIT:-none}
        BUILD_DATE: ${BUILD_DATE:-unknown}
    image: cli-proxy-api-dev
    container_name: cli-proxy-api-dev
    environment:
      DEPLOY: local
      WRITABLE_PATH: /root/.cli-proxy-api
    ports:
      - "8317:8317"
      - "8085:8085"
      - "1455:1455"
      - "54545:54545"
      - "51121:51121"
      - "11451:11451"
    volumes:
      - .:/app
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./.local-config:/root/.cli-proxy-api
      - ./logs:/CLIProxyAPI/logs
    pull_policy: build
    restart: unless-stopped
